export 'local_widget/details _part.dart';
export 'local_widget/details_card.dart';
export 'local_widget/pic_part.dart';
export 'local_widget/title_card.dart';
export 'local_widget/address.dart';
export 'local_widget/edit_profile.dart';
export 'local_widget/indicator_sign.dart';
export 'local_widget/payment_status.dart';
export 'local_widget/status_indicator.dart';
export 'local_widget/thank_you_message.dart';
export '../../data/global_widget/space_widget/space_in_height.dart';
export '../../data/global_widget/text_widget/text_bold.dart';
export '../../data/global_widget/text_widget/text_regular.dart';
export '../../data/global_widget/space_widget/space_in_width.dart';
export '../../data/utils/custom_color.dart';
export '../log_in&sign_uo/view/log_in.dart';
export '../../data/global_widget/custom_app_bar.dart';
export '../checkout/local_widget/title_card.dart';
export '../checkout/local_widget/checkout_item_list.dart';
export '../checkout/local_widget/payment_details.dart';
export '../../data/global_widget/text_widget/text_medium.dart';
export '../../data/global_widget/fill_custom_button.dart';
export 'view/order_details.dart ';