export 'local_widget/button_text.dart';
export 'local_widget/input_form.dart';
export 'local_widget/other_option_text.dart';
export 'local_widget/other option.dart';
export 'local_widget/terms&policy.dart';
export '../../data/global_widget/text_widget/text_bold.dart';
export '../../data/global_widget/text_widget/text_regular.dart';
export '../../data/global_widget/text_widget/text_light_italic.dart';
export '../../data/global_widget/text_widget/text_medium.dart';
export '../../data/global_widget/space_widget/space_in_height.dart';
export '../../data/global_widget/space_widget/space_in_width.dart';
export '../../data/global_widget/sign_button.dart';
export '../../data/utils/custom_color.dart';
export '../nav_bar/nav_bar.dart';
export 'view/sign_up.dart';
export 'view/log_in.dart';